version: "3.4"

networks:
  app_bridge:
    external: true

services:
  web:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: jblog-client_image
    container_name: 'jblog-client_container'
    environment:
      - NODE_ENV=production
    ports:
      - 8081:8081
    networks:
      - app_bridge
    volumes:
      - jblog-client-data:/home/jblog-client/dist
    restart: always

volumes:
  jblog-client-data:
    driver: local
    external: true


