version: "3"

#networks:
#  nginxcontainer_app-network:
#    external: true

services:
  web:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: jblog-client_web
    container_name: 'jblog-client_web_container'
    environment:
    - NODE_ENV=production
    ports:
    - 8081:8081
    restart: always
#    depends_on:
#    - nginx
#    networks:
#    - nginxcontainer_app-network



