version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: jblog-client_web
    container_name: 'jblog-client_web_container'
    environment:
    - NODE_ENV=production
    ports:
    - 8081:8081
    restart: always



