version: "3"

networks:
  nginx-network:
    driver: bridge

services:
#  nginx:
#    user: root
#    build:
#      context: .
#      dockerfile: ./nginx/Dockerfile
#    image: jblog-client_nginx
#    container_name: 'jblog-client_nginx_container'
#    ports:
#    - 80:80
#    - 443:443
#    volumes:
#    - ./nginx/cert:/etc/nginx/conf.d/cert
#    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    restart: always
#    networks:
#    - app-network

  web:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: jblog-client_web
    container_name: 'jblog-client_web_container'
    environment:
    - NODE_ENV=production
    ports:
    - 8081:8081
    restart: always
#    depends_on:
#    - nginx
    networks:
    - nginx-network



