
version: "3"

networks:
  app-network:
    driver: bridge

volumes:
  web:
    #external: true

services:
  # 服务名称
  nginx:
    user: root
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    image: jblog-client_nginx
    # 容器名称
    container_name: 'jblog-client_nginx_container'
    ports:
      -  80:80
      -  443:443
    volumes:
      - web:/usr/share/nginx/html/dist
      - ./nginx/cert:/etc/nginx/conf.d/cert
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #    links:
    #    - web:koaserver #给它取个别名，叫做koaserver
    restart: always
    networks:
      - app-network

  web:
    build:
      context: ./node/
      dockerfile: Dockerfile
    image: jblog-client_web
    container_name: 'jblog-client_web_container'
    environment:
      - NODE_ENV=production
    ports:
      - 8081:8081
    volumes:
      - web:/home/jblog-client/dist
    restart: always
    depends_on:
      - nginx
    #    depends_on:
    #      - mongo
    networks:
      - app-network



#  mongo:
#    build:
#      context: .
#      dockerfile: ./mongo/Dockerfile
#    ports:
#      - 27017:27017
#    volumes:
##      - mongo:/data/db
#    restart: always
#    networks:
#      - app-network

#  docker cp ~/Sites/api-mocker/client/dist mock-nginx:/root


